### ISSUE TITLE
[Bug]: Recorder starting goes too fast in example app.

### ISSUE THREAD

**Issue by drcrallen** [inworld-ai/inworld-web-sdk#89]
### Version

1.9.0

## Steps to reproduce the problem
Was getting the following error on occasion when clicking on the Record icon in the example app with promptness.:

```
DOMException: Failed to execute 'createAnswer' on 'RTCPeerConnection': PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer.
```

## What happened?

The error 
```
DOMException: Failed to execute 'createAnswer' on 'RTCPeerConnection': PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer.
```

I can just try to re-click the record icon or toggle on/off and it seems to get back into a good state.

## What did you expect to happen?

Record voice enables.

## Anything else we should know?

I thought this would fix but looks like it does not. I just got it to reproduce again.
https://github.com/drcrallen/inworld-web-sdk/commit/1ab5948f4b597fcdd90a8b164a6030b95459d0df 

With the above patch I got:
```
Failed starting audio:  DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
DOMException: Failed to execute 'createAnswer' on 'RTCPeerConnection': PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer.

Uncaught (in promise) Error: Audio session is already started
```

**Comment by tshashkova** [comment]
@drcrallen I suppose it happens due to network issues
For exampe, If wi-fi was lost and restored during voice sending

In generally, we are working on reconnect improvements now
And I will take into account this case too

**Comment by tshashkova** [comment]
@drcrallen I could not reproduce `RTCPeerConnection` error, but `Audio session is already started` is generated from SDK side. We should not call it twice.
And if we press on Record icon twice in short time period, isRecording variable in React app still has `false` value. Because we call async function. That's why we call `startRecording` twice.
The same issue occurs regularly if we have slow internet connection. In this case we need more time to finish async function call.

I've replaced `isRecording` by `recordingState`
https://github.com/inworld-ai/inworld-web-sdk/pull/96

Could you try to reproduce you issue with these modifications?
